version: '3.8'

networks:
  fabric_net:

services:

  orderer.example.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer.example.com
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./config/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./config/orderer/msp:/var/hyperledger/orderer/msp
    ports:
      - "7050:7050"
    networks:
      - fabric_net

  peer0.partidoa.example.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.partidoa.example.com
    environment:
      - CORE_PEER_ID=peer0.partidoa.example.com
      - CORE_PEER_ADDRESS=peer0.partidoa.example.com:7051
      - CORE_PEER_LOCALMSPID=PartidoAMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
    command: peer node start
    volumes:
      - ./config/partidoa/msp:/var/hyperledger/peer/msp
    ports:
      - "7051:7051"
    networks:
      - fabric_net

  peer0.partidob.example.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.partidob.example.com
    environment:
      - CORE_PEER_ID=peer0.partidob.example.com
      - CORE_PEER_ADDRESS=peer0.partidob.example.com:8051
      - CORE_PEER_LOCALMSPID=PartidoBMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
    command: peer node start
    volumes:
      - ./config/partidob/msp:/var/hyperledger/peer/msp
    ports:
      - "8051:7051"
    networks:
      - fabric_net

  ca.example.com:
    image: hyperledger/fabric-ca:1.5
    container_name: ca.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_PORT=7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    ports:
      - "7054:7054"
    networks:
      - fabric_net

  cli:
    image: hyperledger/fabric-tools:2.5
    container_name: cli
    tty: true
    environment:
      - CORE_PEER_LOCALMSPID=PartidoAMSP
      - CORE_PEER_ADDRESS=peer0.partidoa.example.com:7051
    working_dir: /workspace
    volumes:
      - ./scripts:/workspace/scripts
      - ./config:/workspace/config
      - ./chaincode:/workspace/chaincode
    networks:
      - fabric_net